package report

import (
	"fmt"
	"strings"
	"time"

	"github.com/mistral-hackathon/triageprof/internal/model"
)

type Reporter struct {
}

func NewReporter() *Reporter {
	return &Reporter{}
}

func (r *Reporter) Generate(findings model.FindingsBundle) (string, error) {
	var sb strings.Builder

	// Header
	sb.WriteString("# Performance Triage Report\n\n")
	sb.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format(time.RFC3339)))

	// Executive Summary
	sb.WriteString("## Executive Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Overall Score**: %d/100\n", findings.Summary.OverallScore))
	sb.WriteString(fmt.Sprintf("- **Top Issues**: %s\n", strings.Join(findings.Summary.TopIssueTags, ", ")))
	if len(findings.Summary.Notes) > 0 {
		sb.WriteString("- **Notes**:\n")
		for _, note := range findings.Summary.Notes {
			sb.WriteString(fmt.Sprintf("  - %s\n", note))
		}
	}
	sb.WriteString("\n")

	// Findings by category
	for _, finding := range findings.Findings {
		sb.WriteString(fmt.Sprintf("## %s: %s\n\n", strings.Title(finding.Category), finding.Title))
		sb.WriteString(fmt.Sprintf("- **Severity**: %s\n", strings.Title(finding.Severity)))
		sb.WriteString(fmt.Sprintf("- **Score**: %d\n", finding.Score))
		sb.WriteString("- **Evidence**:\n")
		sb.WriteString(fmt.Sprintf("  - Profile: %s\n", finding.Evidence.ProfileType))
		sb.WriteString(fmt.Sprintf("  - Artifact: %s\n", finding.Evidence.ArtifactPath))
		sb.WriteString("\n")

		if len(finding.Top) > 0 {
			sb.WriteString("### Top Hotspots\n\n")
			sb.WriteString("| Function | File | Line | Cumulative | Flat |\n")
			sb.WriteString("|----------|------|------|------------|------|\n")
			for _, frame := range finding.Top {
				sb.WriteString(fmt.Sprintf("| %s | %s | %d | %.2f | %.2f |\n",
					frame.Function, frame.File, frame.Line, frame.Cum, frame.Flat))
			}
			sb.WriteString("\n")
		}
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by triageprof*\n")

	return sb.String(), nil
}