package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/mistral-hackathon/triageprof/internal/model"
)

type Plugin struct {
	info model.PluginInfo
}

func main() {
	plugin := &Plugin{
		info: model.PluginInfo{
			Name:       "node-inspector",
			Version:    "0.1.0",
			SDKVersion: "1.0",
			Capabilities: model.Capabilities{
				Targets:  []string{"node"},
				Profiles: []string{"cpu", "heap", "allocs"},
			},
		},
	}

	reader := bufio.NewReader(os.Stdin)
	writer := bufio.NewWriter(os.Stdout)
	defer writer.Flush()

	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			fmt.Fprintf(os.Stderr, "Error reading input: %v\n", err)
			continue
		}

		var req RPCRequest
		if err := json.Unmarshal([]byte(line), &req); err != nil {
			fmt.Fprintf(os.Stderr, "Error parsing JSON: %v\n", err)
			continue
		}

		var result interface{}
		var methodErr error

		switch req.Method {
		case "rpc.info":
			result = plugin.info
		case "rpc.validateTarget":
			var target model.Target
			paramsData, err := json.Marshal(req.Params)
			if err != nil {
				result = nil
				break
			}
			if err := json.Unmarshal(paramsData, &target); err != nil {
				result = nil
				break
			}
			methodErr = plugin.validateTarget(target)
		case "rpc.collect":
			var collectReq model.CollectRequest
			paramsData, err := json.Marshal(req.Params)
			if err != nil {
				result = nil
				break
			}
			if err := json.Unmarshal(paramsData, &collectReq); err != nil {
				result = nil
				break
			}
			result, methodErr = plugin.collect(collectReq)
		default:
			methodErr = fmt.Errorf("unknown method: %s", req.Method)
		}

		resp := RPCResponse{
			JSONRPC: "2.0",
			ID:      req.ID,
		}

		if methodErr != nil {
			resp.Error = &RPCError{
				Code:    -32603,
				Message: methodErr.Error(),
			}
		} else {
			resp.Result = result
		}

		data, _ := json.Marshal(resp)
		fmt.Fprintln(writer, string(data))
		writer.Flush()
	}
}

type RPCRequest struct {
	JSONRPC string      `json:"jsonrpc"`
	Method  string      `json:"method"`
	Params  interface{} `json:"params"`
	ID      int         `json:"id"`
}

type RPCResponse struct {
	JSONRPC string      `json:"jsonrpc"`
	Result  interface{} `json:"result,omitempty"`
	Error   *RPCError   `json:"error,omitempty"`
	ID      int         `json:"id"`
}

type RPCError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data,omitempty"`
}

func (p *Plugin) validateTarget(target model.Target) error {
	if target.Type != "node" {
		return fmt.Errorf("unsupported target type: %s", target.Type)
	}
	if len(target.Command) == 0 {
		return fmt.Errorf("node target requires command to be specified")
	}
	return nil
}

func (p *Plugin) collect(req model.CollectRequest) (model.ArtifactBundle, error) {
	// Create output directory
	if err := os.MkdirAll(req.OutDir, 0755); err != nil {
		return model.ArtifactBundle{}, err
	}

	artifacts := []model.Artifact{}

	// Simulate Node.js profiling - in a real implementation, this would use the Node.js inspector protocol
	// For now, we'll create placeholder files to demonstrate the plugin works

	// Collect CPU profile
	if contains(req.Profiles, "cpu") {
		cpuPath := filepath.Join(req.OutDir, "cpu.pb.gz")
		if err := createPlaceholderFile(cpuPath, "Node.js CPU profile"); err == nil {
			artifacts = append(artifacts, model.Artifact{
				Kind:        "pprof",
				ProfileType: "cpu",
				Path:        cpuPath,
				ContentType: "application/octet-stream",
			})
		}
	}

	// Collect Heap profile
	if contains(req.Profiles, "heap") {
		heapPath := filepath.Join(req.OutDir, "heap.pb.gz")
		if err := createPlaceholderFile(heapPath, "Node.js Heap profile"); err == nil {
			artifacts = append(artifacts, model.Artifact{
				Kind:        "pprof",
				ProfileType: "heap",
				Path:        heapPath,
				ContentType: "application/octet-stream",
			})
		}
	}

	// Collect Allocs profile
	if contains(req.Profiles, "allocs") {
		allocsPath := filepath.Join(req.OutDir, "allocs.pb.gz")
		if err := createPlaceholderFile(allocsPath, "Node.js Allocs profile"); err == nil {
			artifacts = append(artifacts, model.Artifact{
				Kind:        "pprof",
				ProfileType: "allocs",
				Path:        allocsPath,
				ContentType: "application/octet-stream",
			})
		}
	}

	return model.ArtifactBundle{
		Metadata: model.Metadata{
			Timestamp:   time.Now(),
			DurationSec: req.DurationSec,
			Service:     req.Metadata["service"],
			Scenario:    req.Metadata["scenario"],
			GitSha:      req.Metadata["gitSha"],
		},
		Target:    req.Target,
		Artifacts: artifacts,
	}, nil
}

func createPlaceholderFile(path, content string) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	_, err = file.WriteString(fmt.Sprintf("# %s placeholder\n# Generated by node-inspector plugin\n# Timestamp: %s\n", content, time.Now().Format(time.RFC3339)))
	return err
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}